name: mris
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.7.11
  - pip:
    - blosc==1.10.6
    - gevent==21.12.0
    - matplotlib==3.4.2
    - monai==0.8.1
    - numpy==1.21.6
    - pandas==1.3.2
    - progressbar==2.5
    - pydicom==2.3.0
    - sas7bdat==2.2.3
    - scikit-image==0.19.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - simpleitk==2.1.1
    - torch==1.10.1
    - torchvision==0.11.2
    - tqdm==4.62.3

